### ISSUE TITLE
Lau Error during loading: "bit" module not found.

### ISSUE THREAD

**Issue by zvodd** [sm-Fifteen/SteamControllerTools#3]
Tried loading the plugin, but Wireshark is having trouble looking for a library `bit.lua` / `bit.dll`.

Wireshark Version 2.2.5 (v2.2.5-0-g440fd4d)  (Windows x64)

* http://i.imgur.com/FrvsGv6.png
* http://pastebin.com/zfgBY39i

What version(s) of wireshark have been tested and confirmed working?

Is it possible that something like http://bitop.luajit.org/ or http://luaforge.net/projects/bit/ is a required module?

**Comment by sm-Fifteen** [comment]
Bitop is needed, yes. That's curious too, I though it came as part of Wireshark.

Both machine I tested this on run Arch linux, where "bit" seems to work out of the box on wireshark. I'll have to see if I can make it work on other Linux distros the same way as well, or if there's some ghost dependency I didn't account for. Does it work if you try to install bitop or lua 5.2 separately? I'm not sure if Wireshark even uses the same search path as plain lua.

**Comment by zvodd** [comment]
Ok  in Kali Linux (and probably ubuntu/debian) this will fix the error:
```
sudo apt-get install liblua5.1-bitop0
```

Now i'm running into issue #4
No idea about fixing it in windows, is lua embedded in wireshark? 
Not sure how to build __bitop__ module as a dll that will work with windows wireshark builds.

**Comment by sm-Fifteen** [comment]
The doc for bitop recommends using mingw to build the thing. The next step would probably be to move it somewhere in Wireshark's searchpath, so any of those listed on your pastebin. I wonder if I could maybe include it in `delayed` as a binary file.

**Comment by zvodd** [comment]
I had to put `bit.dll` in `C:\Program Files\Wireshark`.
I'm guessing it has to be built with MSVC (as I did), because reasons.
(I've had trouble in the past mixing mingw dlls with MSVC dlls and I'm guessing Wireshark is build with MSVC)

**Comment by sm-Fifteen** [comment]
Thanks, I'll change the the README to account for that.
