### ISSUE TITLE
DissectorTable.get error on load.

### ISSUE THREAD

**Issue by zvodd** [sm-Fifteen/SteamControllerTools#4]
`scPacketTable = DissectorTable.get("sc_packet.msgType")`  is failing to get DissectorTable registered in `init.lua` line 6:

`scPacketTable = DissectorTable.new("sc_packet.msgType", "Steam Controller Packet", ftypes.UINT8, base.HEX)`

```
Lua: Error during loading:
 [string "/home/user/.config/wireshark/plugins/steam_co..."]:6: bad argument #1 to 'get' (DissectorTable_get: no such dissector_table)

Lua: Error during loading:
 [string "/home/user/.config/wireshark/plugins/steam_co..."]:6: bad argument #1 to 'get' (DissectorTable_get: no such dissector_table)

Lua: Error during loading:
 [string "/home/user/.config/wireshark/plugins/steam_co..."]:3: bad argument #1 to 'get' (DissectorTable_get: no such dissector_table)
```

Tested in:

 * Wireshark 2.2.4 Linux (Kali) x64
 * Wireshark 2.2.5 Windows x64

**Comment by sm-Fifteen** [comment]
Wireshark is a bit unpredictable in the order in which it loads its files. Normally, it should load `init.lua` first and the stuff in `delayed` next, but it's a bit tricky to get it to actually do that. One way I found you can trick it in the order you want (on linux, at least) is to rename the `delayed` folder to something else and then back, to update its timestamp. It's not ideal, and I'd really like to find a clean fix for that, but for now that's the best I could manage.

EDIT : Try running `tshark -v` if you need to see the order in which wireshark loads everything. Everything in `delayed` can be loaded out of order, but `init.lua` needs to be loaded first to initialize the dissector tables.

**Comment by sm-Fifteen** [comment]
Solved, thanks for fixing it.
